a = int(input())
b = int(input())
c = int(input())
n = a*b*c
arr = str(n)
print(arr.count('0'))
print(arr.count('1'))
print(arr.count('2'))
print(arr.count('3'))
print(arr.count('4'))
print(arr.count('5'))
print(arr.count('6'))
print(arr.count('7'))
print(arr.count('8'))
print(arr.count('9'))