SELECT FI.ID,FNI.FISH_NAME,FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
ON FI.FISH_TYPE = M.FISH_TYPE
AND FI.LENGTH = M.MAX_LENGTH
ORDER BY FI.ID ASC